services:
  mongo:
    image: mongo:4.4
    container_name: 'mongo'
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db

  user-service:
    build: ./user-service
    container_name: user-service
    ports:
      - 3001:3001
    depends_on:
      - mongo

  task-service:
    build: ./task-service
    container_name: task-service
    ports:
      - 3001:3001
    depends_on:
      - mongo

volumes:
  mongo-data:
